Add harurobo
robosemi/robosemi.github.io pull request #30
Opened 2022-03-20 13:12 UTC by HansRobo

春ロボを追加しましたの！
レビューをお願いしますわ！

2022-03-20 14:10 UTC, ssr-yuki commented on index.md
> +## 協力
セクション直後は空白1行入れてください

2022-03-20 14:13 UTC, ssr-yuki commented on index.md
> +2022年4月より本企画は[関西春ロボコン運営委員会](https://xn--tck4d2b0a0029dol2bn0r.com)と協力関係になりました.
> 本企画は，関西春ロボコンの2022年大会開催において，[関西春ロボコン運営委員会](https://xn--tck4d2b0a0029dol2bn0r.com)と協力することになりました．

とか．ひとまずは単年の協力であることを示しましょう．

2022-03-21 11:10 UTC, HansRobo commented
@ssr-yuki ↑を修正しておりますわ！

2022-03-22 00:27 UTC, HansRobo commented
コンフリクトを解消いたしましたわ！

2022-03-22 05:54 UTC, ssr-yuki requested changes

2022-03-22 05:54 UTC, ssr-yuki commented on index.md
> +「関西春ロボコン運営委員会」が主催されている春ロボコン(関西大会)2022の出場チームを交えたコラボ企画をやります．
鍵かっこが違和感あります。
やります→文語表現にしたい

2022-03-22 05:54 UTC, ssr-yuki commented on index.md
> +
なんか増えてる

2022-03-22 05:54 UTC, ssr-yuki commented on index.md
> +「関西春ロボコン運営委員会」が主催されている春ロボコン(関西大会)2022の出場チームを交えたコラボ企画をやります．
```suggestion
春ロボコン（関西大会）2022の出場チームを交えたコラボ企画を、関西春ロボコン運営委員会と共催します．
```

2022-04-16 07:58 UTC, ssr-yuki approved these changes

2022-04-16 07:58 UTC, merged