RSJ追加ですわ〜
robosemi/robosemi.github.io pull request #42
Opened 2022-09-19 13:24 UTC by HansRobo

2022-09-19 13:35 UTC, ssr-yuki commented on archive/rsj2022.md
> +ロボティクス勉強会運営会は，勉強会発足から約2年間の運営経験を取りまとめ，第40回日本ロボット学会学術講演会（RSJ2022）にてその取り組みなどについて報告しました．
学術講演会のリンクがあると，なお良さそうですわね．
https://ac.rsj-web.org/2022/

2022-09-19 13:35 UTC, ssr-yuki commented on archive/rsj2022.md
> +- 発表題目：ロボティクス勉強会の設立と進展
講演番号 (2A1-04) を追加いたしましょう！

2022-09-19 13:35 UTC, ssr-yuki commented on archive/rsj2022.md
> +- 発表動画：[URL]()
スライドや動画はリンクを貼るのではなく，HTMLで埋め込みたいですわね．
春ロボゼミ2022の講評PDFが参考になるかと存じますわ．

2022-12-25 09:49 UTC, HansRobo commented on archive/rsj2022.md
> +ロボティクス勉強会運営会は，勉強会発足から約2年間の運営経験を取りまとめ，第40回日本ロボット学会学術講演会（RSJ2022）にてその取り組みなどについて報告しました．
文字列自体をリンクにしましたわ〜（伝わって欲しいのですわ〜〜〜！！！）

2022-12-25 09:49 UTC, HansRobo commented on archive/rsj2022.md
> +- 発表題目：ロボティクス勉強会の設立と進展
追加しましてよ

2022-12-25 09:50 UTC, HansRobo commented on archive/rsj2022.md
> +- 発表動画：[URL]()
スライド・動画ともに埋め込みましたわ
〜

2022-12-27 13:47 UTC, ssr-yuki requested changes

2022-12-27 13:47 UTC, ssr-yuki commented on index.md
> +- [第40回日本ロボット学会学術講演会（RSJ2022）発表記録](archive/rsj2022)
```suggestion

- [第40回日本ロボット学会学術講演会（RSJ2022）発表記録](archive/rsj2022)
```

2022-12-27 13:47 UTC, ssr-yuki commented on index.md
```suggestion
```

2022-12-27 13:47 UTC, ssr-yuki commented on index.md
> +
```suggestion
```

2022-12-27 14:01 UTC, ssr-yuki approved these changes
おapproveですわ〜〜〜！

2022-12-27 14:02 UTC, merged