Update main description
robosemi/robosemi.github.io pull request #9
Opened 2021-05-24 16:16 UTC by ssr-yuki

確認・コメントよろしくお願いします！

2021-05-25 06:38 UTC, HansRobo requested changes

2021-05-25 06:38 UTC, HansRobo commented on index.md
> +ロボゼミは，時間無制限の「通常発表」，10程度の「LT（ライトニングトーク）」，そして「懇親会」の3部から構成されます．「通常発表」および「LT」では，毎回発表者を募っております．発表内容としては，例えば
×：10程度の
◯：10分程度の
因みにLTは一般的には5分なのでそこに突っ込む人はいると思う
（自分はいいと思う）

2021-05-25 06:38 UTC, HansRobo commented on index.md
> +
企業の技術紹介と宣伝，とかは流石に入れないほうがいいか...

2021-05-25 06:40 UTC, ssr-yuki commented on index.md
> +
意外とありかもしれない！

2021-05-26 03:18 UTC, HansRobo approved these changes

2021-05-26 04:14 UTC, merged

2021-05-28 10:45 UTC, 7oei commented
ごめん。遅くなりましたが確認しました。いいと思います！